[versions]

assertj = "3.24.2"
errorprone-lib = "2.42.0"
errorprone-plugin = "5.0.0"
gradle-git-properties = "2.5.7"
gradle-versions = "0.52.0"
jacoco = "0.8.13"
junit5 = "6.0.0"
log4j = "2.20.0"
mockito = "5.18.0"
rxtx = "2.1.7"
sonarqube = "6.3.1.5724"

[libraries]

assertj-core = { module = "org.assertj:assertj-core", version.ref = "assertj" }
errorprone = { module = "com.google.errorprone:error_prone_core", version.ref = "errorprone-lib" }
junit5-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit5" }
junit5-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit5" }
junit5-params = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "junit5" }
junit5-platform-launcher = { module = "org.junit.platform:junit-platform-launcher", version.ref = "junit5" }
log4j-api = { module = "org.apache.logging.log4j:log4j-api", version.ref = "log4j" }
log4j-core = { module = "org.apache.logging.log4j:log4j-core", version.ref = "log4j" }
mockito = { module = "org.mockito:mockito-core", version.ref = "mockito" }
rxtx = { module = "org.rxtx:rxtx", version.ref = "rxtx" }

[plugins]

errorprone = { id = "net.ltgt.errorprone", version.ref = "errorprone-plugin" }
git-properties = { id = "com.gorylenko.gradle-git-properties", version.ref = "gradle-git-properties" }
gradle-versions = { id = "com.github.ben-manes.versions", version.ref = "gradle-versions"}
sonarqube = { id = "org.sonarqube", version.ref = "sonarqube" }
